name: Style Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  style-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install tools
      run: sudo apt install cpplint clang-format
    - name: Lint
      run: make lint
    - name: Format Check
      run: make format-check
